name: Pre-release Build
on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller rumps

    - name: Build app with pyinstaller
      run: |
        # Build app using spec with pyinstaller
        pyinstaller cb.spec
      shell: bash

    - name: Rename app output
      run: |
        ls -la dist
        zip dist/Clipboard\ Buddy.app clipboard-buddy.zip
        ls -la dist

    - name: Push to Github Releases
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "Clipboard Buddy"
        files: |
          clipboard-buddy.zip